//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialClub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Career
    {
        public int CareerID { get; set; }
        public string Title { get; set; }
        public string Location { get; set; }
        public string Description { get; set; }
        public string TotalPosition { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public string Department { get; set; }
        public string CareerLevel { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
