//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialClub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackageService
    {
        public int ID { get; set; }
        public Nullable<int> PackageID { get; set; }
        public Nullable<int> ServiceID { get; set; }
        public Nullable<bool> IsSelected { get; set; }
    }
}
